Repository twindle-co/twindle, pull requests merged in 2020-11, with the labels that each got.

#507 json2pdf without any dependency
  playground/cli/spike/simple-pdf-to-json/README.md
  playground/cli/spike/simple-pdf-to-json/simple-pdf-to-json/newjson2pdf.css
  playground/cli/spike/simple-pdf-to-json/simple-pdf-to-json/newjson2pdf.html
  playground/cli/spike/simple-pdf-to-json/simple-pdf-to-json/newjson2pdf.js
  playground/cli/spike/simple-pdf-to-json/simple-pdf-to-json/old codes/oldjson2pdf.html
  playground/cli/spike/simple-pdf-to-json/simple-pdf-to-json/old codes/oldjson2pdf.js
  playground/cli/spike/simple-pdf-to-json/simple-pdf-to-json/output.pdf
  twindle-cli/twitter/utils/tweet-lookup-request.js
Labels: code-review, javascript

#500 third pr
  docs/TEAM.md
  firstpr/vera_nkanmuo.md
Labels: TEST: merge-conflict

#632 Improve pdf layout, add page number
  twindle-cli/renderer/pdf/create-pdf.js
  twindle-cli/renderer/pdf/templates/Thread.hbs
Labels: Merge Conflict
