Repository twindle-co/twindle, pull requests merged in 2020-10, with the labels that each got.

#127 Create mumbi.md
  firstpr/mumbi.md
Labels: user-action

#71 [USER ACTION] Create Scott.md
  firstpr/scott.md
Labels: user-action

#212 Create krypton.md
  firstpr/krypton.md
Labels: review pending

#141 Adding my details
  docs/TEAM.md
  firstpr/ad3rinto.md
Labels: user-action

#234 Third PR
  docs/TEAM.md
Labels: Merge Conflict

#201 docs: updating FAQ with tutorials and tips recopiled from github issues
  ONBOARDING.md
  docs/FAQ.md
Labels: Needs Work

#216 Second PR to fabio.md
  firstpr/fabio.md
Labels: Needs Work

#221 A basic intro about myself
  docs/TEAM.md
  firstpr/rakesh.md
Labels: Merge Conflict

#223 Second PR - Predrag
  firstpr/predrag.md
  firstpr/predrag_stamenkovic.md
Labels: Needs Work

#254 TEAM.md updated - Rajesh
  docs/TEAM.md
Labels: review pending

#159 Third PR: Included myself as an Intermediate developer in the Team file
  docs/TEAM.md
Labels: user-action

#251 second pr from local machine
  firstpr/sravan.md
Labels: review pending

#146 Second PR
  docs/FAQ.md
  firstpr/saurabh_srivastava.md
Labels: user-action

#237 sippeybro.md added
  docs/TEAM.md
  firstpr/sippeybro.md
Labels: review pending

#249 Second PR - Edited my doc
  firstpr/pavan.md
Labels: review pending

#262 Third pr MumbiGachomba04
  .gitignore.gitignore
  docs/TEAM.md
Labels: Needs Work

#224 Added myself to the team
  docs/TEAM.md
Labels: Merge Conflict

#207 Update TEAM.md
  docs/TEAM.md
Labels: Merge Conflict

#256 Create Alasi.md
  docs/TEAM.md
  firstpr/habeeb.md
Labels: Needs Work

#108 first pr ~ blessing
  firstpr/blessing.md
Labels: user-action

#228 added my name in team.md
  docs/TEAM.md
Labels: Merge Conflict

#383 Added my name in TEAM.md
  docs/TEAM.md
Labels: Merge Conflict

#359 Creating PDFs using Puppeteer
  .gitignore
  playground/cli/pdf-from-html-cli/README.md
  playground/cli/pdf-from-html-cli/create-pdf.js
  playground/cli/pdf-from-html-cli/examples/Twindle.html
  playground/cli/pdf-from-html-cli/examples/Twindle.pdf
  playground/cli/pdf-from-html-cli/index.js
  playground/cli/pdf-from-html-cli/package.json
  playground/cli/pdf-from-html-cli/render-template.js
  playground/cli/pdf-from-html-cli/templates/Thread.hbs
  playground/cli/twit_thread.json
  playground/mock/twit-thread.json
Labels: code-review, javascript

#341 Hello world message for epub cli program.
  playground/cli/cli-epub/.gitignore
  playground/cli/cli-epub/epub.js
  playground/cli/cli-epub/index.js
  playground/cli/cli-epub/package-lock.json
  playground/cli/cli-epub/package.json
  playground/cli/cli-epub/readme.md
Labels: code-review, javascript

#380 set up server
  .gitignore
  server/api/index.js
  server/config/index.js
  server/environment.js
  server/index.js
  server/middlewares/index.js
  server/middlewares/request-logger.js
  server/middlewares/twitter.js
  server/package-lock.json
  server/package.json
  server/router/api/index.js
  server/router/index.js
  server/router/pages/index.js
Labels: code-review, javascript

#336 My implementation of issues #288 and #301 - CLI application and Hello World PDF
  playground/cli/twindle_cli_node/README.md
  playground/cli/twindle_cli_node/package-lock.json
  playground/cli/twindle_cli_node/package.json
  playground/cli/twindle_cli_node/twindle.js
  playground/cli/twindle_hello_world_pdf/helloworld.pdf
  playground/cli/twindle_hello_world_pdf/package-lock.json
  playground/cli/twindle_hello_world_pdf/package.json
  playground/cli/twindle_hello_world_pdf/pdf.js
Labels: code-review, javascript

#364 adding node js program for json to PDF
  playground/cli/jsonToPDF/Readme.md
  playground/cli/jsonToPDF/output.css
  playground/cli/jsonToPDF/output.html
  playground/cli/jsonToPDF/output.pdf
  playground/cli/jsonToPDF/package.json
  playground/cli/jsonToPDF/script.js
  playground/cli/jsonToPDF/tweet_template.mustache
  playground/cli/jsonToPDF/twit_thread.json
  playground/cli/script.js
Labels: code-review, javascript

#360 simple-json2pdf
  playground/cli/json2pdf.html
  playground/cli/json2pdf.js
Labels: code-review, javascript

#340 Create pdf from json
  Capture.PNG
  docs/FAQ.md
  playground/cli/pdf-from-json/Readme.md
  playground/cli/pdf-from-json/index.js
  playground/cli/pdf-from-json/package-lock.json
  playground/cli/pdf-from-json/package.json
  playground/cli/pdf-from-json/tweet.pdf
Labels: code-review, javascript, user-action

#378 new pull 3rd pr
  docs/TEAM.md
Labels: Merge Conflict

#519 Included forth PR instructions
  docs/ONBOARDING.md
Labels: review pending

#516 Added avatar profile
  docs/TEAM.md
Labels: review pending

#514 homepage6
  playground/twindleco/homepage/homapage6/home.css
  playground/twindleco/homepage/homapage6/home.html
Labels: review pending

#520 update ONBOARDING.md for 4th PR
  docs/ONBOARDING.md
  docs/TEAM.md
  docs/images/team/kiran_don.jpg
Labels: TEST: merge-conflict

#551 Twitter API refactoring - focus on version 2.0 only
  playground/cli/spike/twitter-api/README.md
  playground/cli/twindle-cli/twitter/README.md
  playground/cli/twindle-cli/twitter/index.js
  playground/cli/twindle-cli/twitter/main.js
  playground/cli/twindle-cli/twitter/misc/README.md
  playground/cli/twindle-cli/twitter/misc/script-version1-searchendpoint.js
  playground/cli/twindle-cli/twitter/misc/script-version1-usertimeline.js
  playground/cli/twindle-cli/twitter/misc/script-version2-conversation.js
  playground/cli/twindle-cli/twitter/output/README.md
  playground/cli/twindle-cli/twitter/output/twitter-api-response.json
  playground/cli/twindle-cli/twitter/package-lock.json
  playground/cli/twindle-cli/twitter/package.json
  playground/cli/twindle-cli/twitter/twitter_responses/response-version1-searchendpoint.json
  playground/cli/twindle-cli/twitter/twitter_responses/response-version1-user-timeline.json
  playground/cli/twindle-cli/twitter/twitter_responses/response-version2-conversation.json
  playground/cli/twindle-cli/twitter/twitter_responses/response-version2-tweetthread.json
  playground/cli/twindle-cli/twitter/utils/tweet-info.js
  playground/cli/twindle-cli/twitter/utils/tweet-processing.js
  playground/cli/twindle-cli/twitter/utils/tweet-utils.js
  playground/cli/twindle-cli/twitter/utils/twitter-api-keys.js
  playground/cli/twindle-cli/twitter/utils/twitter-endpoints.js
Labels: code-review, javascript

#470 Update TEAM.md
  docs/TEAM.md
Labels: TEST: merge-conflict
